language: cpp
os:
- linux
sudo: required
dist: trusty
compiler:
- clang
- gcc
addons:
  apt:
    packages:
    - autopoint
    - gettext
    - libeigen3-dev
    - tcl8.6-dev
    - libmysqlclient-dev
    - libpq-dev
    - libxerces-c-dev
    - libglm-dev
    - libglfw-dev
script:
- ./autogen.sh
- CXXFLAGS='-I/usr/include/eigen3 -I/usr/include/mysql -I/usr/include/tcl8.6' ./configure --prefix=$HOME --with-server --with-tcl --with-mysql --with-pgsql --with-client
- make
- make check
