language: cpp
os:
- linux
sudo: required
dist: trusty
compiler:
- clang
- gcc
addons:
  apt:
    packages:
    - autopoint
    - gettext
    - tcl8.6-dev
    - libmysqlclient-dev
    - libpq-dev
    - libxerces-c-dev
    - libglm-dev
    - libglfw-dev
script:
- ./autogen.sh
- ./configure --prefix=$HOME --with-server --with-tcl --with-mysql --with-pgsql --with-client
- make
- make check
