language: cpp
jobs:
  include:
    - os: linux
      dist: trusty
      compiler: clang
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: clang
    - os: linux
      dist: xenial
      compiler: gcc
addons:
  apt:
    packages:
    - autopoint
    - cmake
    - tcl8.6-dev
    - libboost-dev
    - libboost-locale-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - liblua5.2-dev
    - libmysqlclient-dev
    - libpq-dev
    - libglm-dev
    - libfreetype6-dev
    - libwrap0-dev
    - x11proto-randr-dev
    - xorg-dev
before_script:
- wget https://github.com/glfw/glfw/releases/download/3.2/glfw-3.2.zip -O /tmp/glfw-3.2.zip
- unzip /tmp/glfw-3.2.zip
- pushd glfw-3.2 && cmake -DBUILD_SHARED_LIBS=ON -DLIB_SUFFIX=64 -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF && make && sudo make install && popd && rm -rf glfw-3.2
script:
- ./autogen.sh
- CXXFLAGS='-I/usr/include/freetype2' ./configure --prefix=$HOME --with-server --with-lua --with-lua-includes=/usr/include/lua5.2 --with-python --with-tcl --with-tcl-includes=/usr/include/tcl8.6 --with-mysql --with-mysql-includes=/usr/include/mysql --with-pgsql --with-client --enable-profile
- make
- make check
after_script:
- for file in $(grep -l FAIL test/*.trs | sed -e 's/trs$/log/') ; do echo "$file" ; echo ; cat $file ; echo ; done
