name: 'build-and-test'
description: 'Build and test'

runs:
  using: 'composite'
  steps:
    - name: Set up environment
      run: |
        sudo apt-get install autopoint libboost-dev libboost-locale-dev libfreetype6-dev libgl1-mesa-dev libglfw3-dev libglm-dev libglu1-mesa-dev libltdl-dev liblua5.2-dev libmysqlclient-dev libpq-dev libpython3-dev python3-dev tcl8.6-dev x11proto-randr-dev xorg-dev
      shell: bash

    - name: Check out submodules
      run: |
        git submodule update --init --recursive
      shell: bash

    - name: Build
      run: |
        ./autogen.sh
        CXXFLAGS='-I/usr/include/freetype2' ./configure --prefix=/usr --with-server --with-lua --with-lua-includes=/usr/include/lua5.2 --with-python --with-tcl --with-tcl-includes=/usr/include/tcl8.6 --with-mysql --with-mysql-includes=/usr/include/mysql --with-pgsql --with-client --enable-debug --enable-profile
        make
      shell: bash

    - name: Test
      run: |
        make check
      shell: bash
